### PR TITLE
Use withSystemTempDirectory to clean up temporary directories

### LINKED ISSUE #26: Use bracket to ensure deletion of temporary directories
* https://github.com/owickstrom/komposition/blob/064a2a8561200481ac10e16a8920be6eafd37e38/src/Komposition/Render/FFmpeg.hs#L338
* https://github.com/owickstrom/komposition/blob/064a2a8561200481ac10e16a8920be6eafd37e38/src/Komposition/Import/Audio.hs#L159
* Any others?

### PR DESCRIPTION
**Pull request by tfausak**
Fixes #26.

### CODE REVIEW

**Comment by owickstrom** [comment]
Hey! Thanks for the PR. There seems to be a problem, though, I think with binding the pipes Producer in the `withSystemTempDirectory` combinator's inner action. IIRC, this is why I didn't use some bracket-like approach in the first place, because I didn't figure out how to do it with pipes.

**Comment by tfausak** [comment]
Ah, interesting! I'm not actually familiar with Pipes and hoped that this would work. I couldn't get things set up on my local machine, so I figured I'd throw up a PR for discussion and to see what Travis CI said about it. 

That being said, maybe `bracket` from `pipes-safe` is the thing to use here? https://hackage.haskell.org/package/pipes-safe-2.3.1/docs/Pipes-Safe.html#v:bracket

**Comment by owickstrom** [comment]
Cool. Yeah, I think `pipes-safe` should work, as the `SafeT` transformer is already used.

**Comment by tfausak** [comment]
Great! I'll try to update this PR soon.

**Comment by tfausak** [comment]
I think this is ready for review now!

**Comment by owickstrom** [comment]
Looks great, @tfausak! Thank you for the PR. :raised_hands:

**Pull request merged**
