### PR TITLE
Convert audio names to md5 digest - WIP

### LINKED ISSUE #25: Content-addressable directory name for classified audio parts
Use the hash of the original audio file as the name for the classified audio parts directory, to avoid collisionss, and to enable reuse (importing and classifying the same audio file would could reuse any old results).

https://github.com/owickstrom/komposition/blob/064a2a8561200481ac10e16a8920be6eafd37e38/src/Komposition/Import/Audio.hs#L164-L170

### PR DESCRIPTION
**Pull request by akilegaspi**
**Description: Extracts the base name of the audio file and transforms the base name into an md5 digest**

This pull requests fixes #25, by @owickstrom 

*Make sure to describe (where applicable):*

- Added `pureMD5-2.1.3` Package
- Included `bytestring` Package

**Checklist:**

Please make sure to check the following items (that are applicable.)

- [x] Doesn't duplicate any existing PR
- [ ] Automated tests added

**How to test:**

**TODO: Testing instructions for reviewer.**

### CODE REVIEW

**Comment by akilegaspi** [comment]
Still have to create automated tests for this one also

**Comment by akilegaspi** [comment]
Sorry, I haven't been able to checkout the PR for awhile now but ok, so if I understood it correctly, we use the contents of the file to create a hashname for the audio chunk.

Also what do you mean by "non-classifying copy?"

**Comment by akilegaspi** [comment]
In accordance with #76 , I think it would be better if we created a helper module for generating a hash given `Cipher -> ByteString -> String`.

**Comment by Cmdv** [comment]
@akilegaspi feel free to help out with the helper function, I started making something but I'm using the file name to do the hashing when I think from comments we need to use the file content?

https://github.com/owickstrom/komposition/pull/76/files#diff-c0ab36ff8cac8d74b3774e1a4cb62225

**Pull request closed without merging**
